sudo: true

language: java

before_cache:
  - rm -rf $HOME/.m2/repository/org/antlr
cache:
  timeout: 600
  directories:
  - $HOME/.m2
  - $HOME/Library/Caches/Antlr4
  - $HOME/Library/Caches/Homebrew

stages:
  - smoke-test
  - main-test
  - extended-test

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++-5
        - GROUP=LEXER
      stage: main-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - g++-5
            - uuid-dev
            - clang-3.7
    - os: linux
      dist: trusty
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++-5
        - GROUP=PARSER
      stage: main-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - g++-5
            - uuid-dev
            - clang-3.7
    - os: linux
      dist: trusty
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++-5
        - GROUP=RECURSION
      stage: main-test
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - g++-5
            - uuid-dev
            - clang-3.7
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=cpp
        - GROUP=LEXER
      stage: extended-test
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=cpp
        - GROUP=PARSER
      stage: extended-test
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=cpp
        - GROUP=RECURSION
      stage: extended-test
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=swift
        - GROUP=LEXER
      stage: main-test
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=swift
        - GROUP=PARSER
      stage: main-test
    - os: osx
      compiler: clang
      osx_image: xcode10.2
      env:
        - TARGET=swift
        - GROUP=RECURSION
      stage: main-test
    - os: linux
      dist: xenial
      compiler: clang
      env:
       - TARGET=swift
       - GROUP=ALL
      stage: extended-test
    - os: osx
      osx_image: xcode10.2
      env:
        - TARGET=dotnet
        - GROUP=LEXER
      stage: extended-test
    - os: osx
      osx_image: xcode10.2
      env:
        - TARGET=dotnet
        - GROUP=PARSER
      stage: extended-test
    - os: osx
      osx_image: xcode10.2
      env:
        - TARGET=dotnet
        - GROUP=RECURSION
      stage: extended-test
    - os: linux
      dist: trusty
      jdk: openjdk7
      env: TARGET=java
      stage: extended-test
    - os: linux
      jdk: openjdk8
      env: TARGET=java
      stage: smoke-test
    - os: linux
      jdk: openjdk8
      env: TARGET=csharp
      stage: main-test
    - os: linux
      language: php
      php:
        - 7.2
      jdk: openjdk8
      env: TARGET=php
      stage: main-test
    - os: linux
      jdk: openjdk8
      dist: trusty
      env:
        - TARGET=dotnet
        - GROUP=LEXER
      stage: extended-test
    - os: linux
      jdk: openjdk8
      dist: trusty
      env:
        - TARGET=dotnet
        - GROUP=PARSER
      stage: extended-test
    - os: linux
      jdk: openjdk8
      dist: trusty
      env:
        - TARGET=dotnet
        - GROUP=RECURSION
      stage: extended-test
    - os: linux
      jdk: openjdk8
      env: TARGET=python2
      stage: main-test
    - os: linux
      jdk: openjdk8
      env: TARGET=python3
      addons:
        apt:
          sources:
            - deadsnakes # source required so it finds the package definition below
          packages:
            - python3.7
      stage: main-test
    - os: linux
      dist: trusty
      jdk: openjdk8
      env: TARGET=javascript
      stage: main-test
    - os: linux
      dist: trusty
      jdk: openjdk8
      env: TARGET=go
      stage: main-test
    - os: linux
      arch: s390x
      dist: bionic
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++
        - GROUP=LEXER
      stage: main-test
      addons:
        apt:
          packages:
            - g++
            - uuid-dev
            - clang
            - maven	
    - os: linux
      arch: s390x
      dist: bionic
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++
        - GROUP=PARSER
      stage: main-test
      addons:
        apt:
          packages:
            - g++
            - uuid-dev
            - clang
            - maven		
    - os: linux
      arch: s390x
      dist: bionic
      compiler: clang
      jdk: openjdk8
      env:
        - TARGET=cpp
        - CXX=g++
        - GROUP=RECURSION
      stage: main-test
      addons:
        apt:
          packages:
            - g++
            - uuid-dev
            - clang
            - maven    
    - os: linux
      arch: s390x
      dist: bionic
      jdk: openjdk7
      env: TARGET=java
      addons:
        apt:
          - maven
      stage: extended-test	  
    - os: linux
      arch: s390x
      jdk: openjdk8
      dist: bionic
      env: TARGET=java
      addons:
        apt:
          - maven
      stage: smoke-test
    - os: linux
      arch: s390x
      dist: bionic
      language: php
      php:
        - 7.2
      jdk: openjdk8
      env: TARGET=php
      addons:
        apt:
          - maven
      stage: main-test  
    - os: linux
      arch: s390x
      dist: bionic
      jdk: openjdk8
      env: TARGET=python2
      addons:
        apt:
          - maven
      stage: main-test 
    - os: linux
      arch: s390x
      dist: bionic
      jdk: openjdk8
      env: TARGET=python3
      addons:
        apt:
          packages:
            - python3.7
            - maven
      stage: main-test  
    - os: linux
      arch: s390x
      dist: bionic
      jdk: openjdk8
      env: TARGET=javascript
      addons:
        apt:
          - maven
      stage: main-test
    - os: linux
      arch: s390x
      dist: bionic
      jdk: openjdk8
      env: TARGET=go
      addons:
        apt:
          - maven
          - golang
      stage: main-test

before_install:
  - f="./.travis/before-install-$TRAVIS_OS_NAME-$TARGET.sh"; ! [ -x "$f" ] || "$f"
  - ps -aef
  - if [[ $(uname -m) != 's390x' ]]; then 
     wget http://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.5.41/linux/s390x/ibm-java-s390x-sdk-8.0-5.41.bin ;
     wget https://raw.githubusercontent.com/zos-spark/scala-workbench/master/files/installer.properties.java && tail -n +3 installer.properties.java | tee installer.properties && cat installer.properties && chmod +x ibm-java-s390x-sdk-8.0-5.41.bin ;
     sudo ./ibm-java-s390x-sdk-8.0-5.41.bin -r installer.properties ;
     export JAVA_HOME=/opt/ibm/java ;
     export JVM_DIR=$JAVA_HOME/jre/lib/s390x/default && export JAVA_JVM_LIBRARY=$JAVA_HOME/jre/lib/s390x/default/libjvm.so && export JAVA_TEST_LDFLAGS="-L$JVM_DIR -R$JVM_DIR -Wl,-ljvm -ldl" ;
     ls /opt/ibm/java/bin && echo $PATH ;
     export PATH=$JAVA_HOME/bin:$PATH ;
     java -version ;
    fi

script:
  - |
    cd runtime-testsuite;
    ps -aef ;
    mvn -q -Dparallel=methods -DthreadCount=4 -Dtest=java.* test ;
    cd ../tool-testsuite ;
    mvn test ;
    #travis_wait 40 ../.travis/run-tests-$TARGET.sh;
    rc=$?;
    cat target/surefire-reports/*.dumpstream || true;
    exit $rc
